import { pageMetadata } from '@/lib/seo';
import Link from 'next/link';
import { ArrowRight, CircleCheck, MessageCircle } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Reveal from '@/components/Reveal';
import MaintenanceFeature from '@/components/MaintenanceFeature';
import { SERVICES } from '@/data/services';
import { getWhatsAppUrl } from '@/lib/whatsapp';
export const metadata = pageMetadata('Renovation & Building Services Petaling Jaya | Promanage', 'Renovation, house extensions, wet works, interior design, project management and JMB building maintenance in Petaling Jaya and Klang Valley.', '/services');
export default function ServicesPage(){return <div className="site-shell"><Navbar /><main id="main-content"><section className="page-heading"><div className="container"><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/">Home</Link><span aria-hidden="true">/</span><span>Services</span></nav><p className="eyebrow">Our Expertise</p><h1>Thoughtfully designed.<br />Beautifully built.</h1><p className="section-copy">Renovation, house extensions, interior design and building maintenance in Petaling Jaya and Klang Valley. Five services, coordinated around your property.</p></div></section>{SERVICES.map(service=><section key={service.id} id={service.id} className="section"><Reveal className="container service-detail"><div><p className="eyebrow">{service.title}</p><h2>{service.short}</h2><p className="section-copy">{service.description}</p><ul className="scope-list">{service.scope.map(item=><li key={item}><CircleCheck size={23} aria-hidden="true" />{item}</li>)}</ul><Link className="text-link service-detail-link" href={`/services/${service.id}`}>Explore {service.title} <ArrowRight size={20} aria-hidden="true" /></Link><a className="button button-gold" href={getWhatsAppUrl(`Hello Benedict Tan, I would like to enquire about ${service.title}.`)} target="_blank" rel="noopener noreferrer"><MessageCircle size={21} aria-hidden="true" />Discuss {service.title} <ArrowRight size={20} aria-hidden="true" /></a></div><figure className="detail-photo"><img src={service.image} alt={service.alt} width={1200} height={900} loading="lazy" /></figure></Reveal></section>)}<div className="container" style={{paddingBottom:70}}><MaintenanceFeature /></div></main><Footer /></div>;}
