'use client';
import { useEffect, useRef, useState, useId } from 'react';
import Link from 'next/link';
import { ArrowRight, ChevronLeft, ChevronRight, Search, X, MessageCircle } from 'lucide-react';
import { PORTFOLIO_PROJECTS, ProjectMedia, ProjectCategory } from '@/data/portfolio-data';
import { getWhatsAppUrl } from '@/lib/whatsapp';

function ProjectCard({ project, featured, onOpen }: { project: ProjectMedia; featured: boolean; onOpen: (project: ProjectMedia, index: number) => void }) {
  const [index, setIndex] = useState(0);
  const start = useRef<number | null>(null);
  const go = (step: number) => setIndex(current => (current + step + project.images.length) % project.images.length);
  const image = project.images[index];
  return <article className={`project-card ${featured ? 'featured-card' : ''}`}><div className="project-image-wrap" onTouchStart={event => { start.current = event.changedTouches[0].clientX; }} onTouchEnd={event => { if (start.current !== null) { const distance = event.changedTouches[0].clientX - start.current; if (Math.abs(distance) > 45) go(distance < 0 ? 1 : -1); start.current = null; } }} onKeyDown={event => { if (event.key === 'ArrowLeft' || event.key === 'ArrowRight') { event.preventDefault(); go(event.key === 'ArrowRight' ? 1 : -1); } }}><button type="button" className="project-image-button" onClick={() => onOpen(project,index)} aria-label={`Enlarge ${project.title}, image ${index+1}`}><img src={image.src} alt={image.alt} width={image.width} height={image.height} loading="lazy" /></button><span className="project-count" aria-live="polite">{index+1} / {project.images.length}</span><button type="button" className="circle-control project-prev" onClick={() => go(-1)} aria-label={`Previous image of ${project.title}`}><ChevronLeft aria-hidden="true" /></button><button type="button" className="circle-control project-next" onClick={() => go(1)} aria-label={`Next image of ${project.title}`}><ChevronRight aria-hidden="true" /></button></div><h3><button type="button" onClick={() => onOpen(project,index)}>{project.title}</button></h3><div className="project-meta"><p className="project-category">{project.category} · {project.location}</p><p>{project.description}</p><button type="button" className="text-link" onClick={() => onOpen(project,index)}>View Project Gallery <ArrowRight size={21} aria-hidden="true" /></button>{['diamond-residence-semenyih', 'dahlia-rawang'].includes(project.id) && <Link className="text-link project-story-link" href={`/portfolio/${project.id}`}>Read the project details <ArrowRight size={21} aria-hidden="true" /></Link>}</div></article>;
}
function ProjectLightbox({ project, initialIndex, onClose }: { project: ProjectMedia; initialIndex: number; onClose: () => void }) {
  const dialog = useRef<HTMLDialogElement>(null);
  const previousFocus = useRef<HTMLElement | null>(null);
  const [index,setIndex] = useState(initialIndex);
  const titleId = useId();
  const start = useRef<number | null>(null);
  const go = (step: number) => setIndex(current => (current+step+project.images.length)%project.images.length);
  useEffect(() => { const element = dialog.current; previousFocus.current = document.activeElement as HTMLElement; const overflow = document.body.style.overflow; document.body.style.overflow='hidden'; element?.showModal(); return () => { document.body.style.overflow=overflow; if (!element?.isConnected) previousFocus.current?.focus(); }; }, []);
  const image=project.images[index];
  return <dialog ref={dialog} aria-labelledby={titleId} onCancel={event => { event.preventDefault(); onClose(); }} onKeyDown={event => { if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();go(event.key==='ArrowRight'?1:-1);} }} className="project-dialog"><div className="lightbox-inner"><div className="lightbox-header"><div><h2 id={titleId}>{project.title}</h2><p>{project.location}</p></div><button className="circle-control" type="button" autoFocus onClick={onClose} aria-label="Close project gallery"><X aria-hidden="true" /></button></div><div className="lightbox-image" onTouchStart={event => { start.current=event.changedTouches[0].clientX; }} onTouchEnd={event => { if(start.current!==null){const d=event.changedTouches[0].clientX-start.current;if(Math.abs(d)>45)go(d<0?1:-1);start.current=null;} }}><img src={image.src} alt={image.alt} width={image.width} height={image.height} /></div><div className="lightbox-controls"><button type="button" className="circle-control" onClick={()=>go(-1)} aria-label="Previous project image"><ChevronLeft aria-hidden="true" /></button><span aria-live="polite">Image {index+1} of {project.images.length}</span><button type="button" className="circle-control" onClick={()=>go(1)} aria-label="Next project image"><ChevronRight aria-hidden="true" /></button></div><div className="lightbox-thumbnails" aria-label="Choose a project image">{project.images.map((item,n)=><button type="button" key={item.src} onClick={()=>setIndex(n)} aria-label={`Show image ${n+1}`} aria-pressed={index===n}><img src={item.src} alt="" loading="lazy" /></button>)}</div><a href={getWhatsAppUrl(`Hello Benedict Tan, I would like to discuss a project similar to ${project.title}.`)} target="_blank" rel="noopener noreferrer" className="button button-gold lightbox-enquiry"><MessageCircle size={22} aria-hidden="true" />Enquire About a Similar Project</a></div></dialog>;
}
export default function ProjectGallery({ featured=false }: { featured?:boolean }) {
  const [category,setCategory]=useState<ProjectCategory|'All'>('All');
  const [query,setQuery]=useState('');
  const [active,setActive]=useState<{project:ProjectMedia;index:number}|null>(null);
  const categories:(ProjectCategory|'All')[]=['All','Residential','Commercial','Renovation','Construction','Design Concepts'];
  const filtered=featured?PORTFOLIO_PROJECTS.slice(0,3):PORTFOLIO_PROJECTS.filter(project=>(category==='All'||project.category===category)&&`${project.title} ${project.location} ${project.description}`.toLowerCase().includes(query.trim().toLowerCase()));
  return <div>{!featured&&<><div className="project-filters" aria-label="Filter projects by category">{categories.map(item=><button type="button" key={item} onClick={()=>setCategory(item)} aria-pressed={category===item}>{item} ({item==='All'?PORTFOLIO_PROJECTS.length:PORTFOLIO_PROJECTS.filter(p=>p.category===item).length})</button>)}</div><label className="project-search"><Search size={22} aria-hidden="true" /><span className="sr-only">Search projects or locations</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search project or location" /></label><p className="project-results" aria-live="polite">{filtered.length} {filtered.length===1?'project':'projects'}</p></>}<div className={`project-grid ${featured?'featured-grid':''}`}>{filtered.map(project=><ProjectCard key={project.id} project={project} featured={featured} onOpen={(project,index)=>setActive({project,index})} />)}</div>{filtered.length===0&&<p className="empty-state">No projects match your search. Try another name or location.</p>}{active&&<ProjectLightbox project={active.project} initialIndex={active.index} onClose={()=>setActive(null)} />}</div>;
}
